2021-07-26 17:14:14,734 DEBUG    root            Loaded Command Group: ['gcloud', 'ai_platform']
2021-07-26 17:14:14,735 DEBUG    root            Loaded Command Group: ['gcloud', 'ai-platform', 'local']
2021-07-26 17:14:14,738 DEBUG    root            Loaded Command Group: ['gcloud', 'ai-platform', 'local', 'predict']
2021-07-26 17:14:14,744 DEBUG    root            Running [gcloud.ai-platform.local.predict] with arguments: [--json-instances: "x_input.json", --model-dir: "output"]
2021-07-26 17:14:14,744 INFO     ___FILE_ONLY___ If the signature defined in the model is not serving_default then you must specify it via --signature-name flag, otherwise the command may fail.

2021-07-26 17:14:17,225 DEBUG    root            (gcloud.ai-platform.local.predict) b'WARNING:tensorflow:From /opt/conda/lib/python3.7/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.\nInstructions for updating:\nnon-resource variables are not supported in the long term\n2021-07-26 17:14:16.699277: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.\nWARNING:tensorflow:From /usr/lib/google-cloud-sdk/lib/third_party/ml_sdk/cloud/ml/prediction/frameworks/tf_prediction_lib.py:236: load (from tensorflow.python.saved_model.loader_impl) is deprecated and will be removed in a future version.\nInstructions for updating:\nThis function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.loader.load or tf.compat.v1.saved_model.load. There will be a new function for importing SavedModels in Tensorflow 2.0.\nWARNING:tensorflow:From /usr/lib/google-cloud-sdk/lib/third_party/ml_sdk/cloud/ml/prediction/frameworks/tf_prediction_lib.py:236: load (from tensorflow.python.saved_model.loader_impl) is deprecated and will be removed in a future version.\nInstructions for updating:\nThis function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.loader.load or tf.compat.v1.saved_model.load. There will be a new function for importing SavedModels in Tensorflow 2.0.\n2021-07-26 17:14:16.733379: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 2200210000 Hz\nWARNING:root:Error updating signature __saved_model_init_op: The name \'NoOp\' refers to an Operation, not a Tensor. Tensor names must be of the form "<op_name>:<output_index>".\n[[-0.0118479924 -0.245696574 0.00204007351 ... 0.507244527 1.56881642 -2.29240727]\n [-0.089297764 -2.43969703 1.08598244 ... 1.1627239 -0.445244908 0.262044191]\n [1.0680995 -1.70710838 -1.21784294 ... -0.689409077 1.00506401 -0.211256862]\n ...\n [0.788459301 -0.581971109 1.67335248 ... -0.772517741 0.758522451 0.202729031]\n [0.507160246 0.0075546694 -0.344337076 ... -0.865982115 -1.21321929 0.285919338]\n [0.726684809 0.281388 -1.41211927 ... -0.179163426 0.193531767 2.77917266]]\nTraceback (most recent call last):\n  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/command_lib/ml_engine/local_predict.py", line 184, in <module>\n    main()\n  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/command_lib/ml_engine/local_predict.py", line 179, in main\n    signature_name=args.signature_name)\n  File "/usr/lib/google-cloud-sdk/lib/third_party/ml_sdk/cloud/ml/prediction/prediction_lib.py", line 102, in local_predict\n    predictions = model.predict(instances, signature_name=signature_name)\n  File "/usr/lib/google-cloud-sdk/lib/third_party/ml_sdk/cloud/ml/prediction/prediction_utils.py", line 262, in predict\n    predicted_outputs, original_input=instances, stats=stats, **kwargs)\n  File "/usr/lib/google-cloud-sdk/lib/third_party/ml_sdk/cloud/ml/prediction/frameworks/tf_prediction_lib.py", line 515, in postprocess\n    postprocessed_outputs = list(postprocessed_outputs)\n  File "/usr/lib/google-cloud-sdk/lib/third_party/ml_sdk/cloud/ml/prediction/frameworks/tf_prediction_lib.py", line 152, in rowify\n    "outputs." % sizes_dict)\ncloud.ml.prediction.prediction_utils.PredictionError: There was a problem processing the outputs: Bad output from running tensorflow session: outputs had differing sizes in the batch (outer) dimension. See the outputs and their size: {\'output\': 100, \'other\': 1, \'key\': 100}. Check your model for bugs that effect the size of the outputs. (Error code: 3)\n'
Traceback (most recent call last):
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 984, in Execute
    resources = calliope_command.Run(cli=self, args=args)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 809, in Run
    resources = command_instance.Run(args)
  File "/usr/lib/google-cloud-sdk/lib/surface/ai_platform/local/predict.py", line 100, in Run
    signature_name=args.signature_name)
  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/command_lib/ml_engine/local_utils.py", line 112, in RunPredict
    raise LocalPredictRuntimeError(err)
googlecloudsdk.command_lib.ml_engine.local_utils.LocalPredictRuntimeError: b'WARNING:tensorflow:From /opt/conda/lib/python3.7/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.\nInstructions for updating:\nnon-resource variables are not supported in the long term\n2021-07-26 17:14:16.699277: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.\nWARNING:tensorflow:From /usr/lib/google-cloud-sdk/lib/third_party/ml_sdk/cloud/ml/prediction/frameworks/tf_prediction_lib.py:236: load (from tensorflow.python.saved_model.loader_impl) is deprecated and will be removed in a future version.\nInstructions for updating:\nThis function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.loader.load or tf.compat.v1.saved_model.load. There will be a new function for importing SavedModels in Tensorflow 2.0.\nWARNING:tensorflow:From /usr/lib/google-cloud-sdk/lib/third_party/ml_sdk/cloud/ml/prediction/frameworks/tf_prediction_lib.py:236: load (from tensorflow.python.saved_model.loader_impl) is deprecated and will be removed in a future version.\nInstructions for updating:\nThis function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.loader.load or tf.compat.v1.saved_model.load. There will be a new function for importing SavedModels in Tensorflow 2.0.\n2021-07-26 17:14:16.733379: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 2200210000 Hz\nWARNING:root:Error updating signature __saved_model_init_op: The name \'NoOp\' refers to an Operation, not a Tensor. Tensor names must be of the form "<op_name>:<output_index>".\n[[-0.0118479924 -0.245696574 0.00204007351 ... 0.507244527 1.56881642 -2.29240727]\n [-0.089297764 -2.43969703 1.08598244 ... 1.1627239 -0.445244908 0.262044191]\n [1.0680995 -1.70710838 -1.21784294 ... -0.689409077 1.00506401 -0.211256862]\n ...\n [0.788459301 -0.581971109 1.67335248 ... -0.772517741 0.758522451 0.202729031]\n [0.507160246 0.0075546694 -0.344337076 ... -0.865982115 -1.21321929 0.285919338]\n [0.726684809 0.281388 -1.41211927 ... -0.179163426 0.193531767 2.77917266]]\nTraceback (most recent call last):\n  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/command_lib/ml_engine/local_predict.py", line 184, in <module>\n    main()\n  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/command_lib/ml_engine/local_predict.py", line 179, in main\n    signature_name=args.signature_name)\n  File "/usr/lib/google-cloud-sdk/lib/third_party/ml_sdk/cloud/ml/prediction/prediction_lib.py", line 102, in local_predict\n    predictions = model.predict(instances, signature_name=signature_name)\n  File "/usr/lib/google-cloud-sdk/lib/third_party/ml_sdk/cloud/ml/prediction/prediction_utils.py", line 262, in predict\n    predicted_outputs, original_input=instances, stats=stats, **kwargs)\n  File "/usr/lib/google-cloud-sdk/lib/third_party/ml_sdk/cloud/ml/prediction/frameworks/tf_prediction_lib.py", line 515, in postprocess\n    postprocessed_outputs = list(postprocessed_outputs)\n  File "/usr/lib/google-cloud-sdk/lib/third_party/ml_sdk/cloud/ml/prediction/frameworks/tf_prediction_lib.py", line 152, in rowify\n    "outputs." % sizes_dict)\ncloud.ml.prediction.prediction_utils.PredictionError: There was a problem processing the outputs: Bad output from running tensorflow session: outputs had differing sizes in the batch (outer) dimension. See the outputs and their size: {\'output\': 100, \'other\': 1, \'key\': 100}. Check your model for bugs that effect the size of the outputs. (Error code: 3)\n'
2021-07-26 17:14:17,226 ERROR    root            (gcloud.ai-platform.local.predict) b'WARNING:tensorflow:From /opt/conda/lib/python3.7/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.\nInstructions for updating:\nnon-resource variables are not supported in the long term\n2021-07-26 17:14:16.699277: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.\nWARNING:tensorflow:From /usr/lib/google-cloud-sdk/lib/third_party/ml_sdk/cloud/ml/prediction/frameworks/tf_prediction_lib.py:236: load (from tensorflow.python.saved_model.loader_impl) is deprecated and will be removed in a future version.\nInstructions for updating:\nThis function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.loader.load or tf.compat.v1.saved_model.load. There will be a new function for importing SavedModels in Tensorflow 2.0.\nWARNING:tensorflow:From /usr/lib/google-cloud-sdk/lib/third_party/ml_sdk/cloud/ml/prediction/frameworks/tf_prediction_lib.py:236: load (from tensorflow.python.saved_model.loader_impl) is deprecated and will be removed in a future version.\nInstructions for updating:\nThis function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.loader.load or tf.compat.v1.saved_model.load. There will be a new function for importing SavedModels in Tensorflow 2.0.\n2021-07-26 17:14:16.733379: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 2200210000 Hz\nWARNING:root:Error updating signature __saved_model_init_op: The name \'NoOp\' refers to an Operation, not a Tensor. Tensor names must be of the form "<op_name>:<output_index>".\n[[-0.0118479924 -0.245696574 0.00204007351 ... 0.507244527 1.56881642 -2.29240727]\n [-0.089297764 -2.43969703 1.08598244 ... 1.1627239 -0.445244908 0.262044191]\n [1.0680995 -1.70710838 -1.21784294 ... -0.689409077 1.00506401 -0.211256862]\n ...\n [0.788459301 -0.581971109 1.67335248 ... -0.772517741 0.758522451 0.202729031]\n [0.507160246 0.0075546694 -0.344337076 ... -0.865982115 -1.21321929 0.285919338]\n [0.726684809 0.281388 -1.41211927 ... -0.179163426 0.193531767 2.77917266]]\nTraceback (most recent call last):\n  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/command_lib/ml_engine/local_predict.py", line 184, in <module>\n    main()\n  File "/usr/lib/google-cloud-sdk/lib/googlecloudsdk/command_lib/ml_engine/local_predict.py", line 179, in main\n    signature_name=args.signature_name)\n  File "/usr/lib/google-cloud-sdk/lib/third_party/ml_sdk/cloud/ml/prediction/prediction_lib.py", line 102, in local_predict\n    predictions = model.predict(instances, signature_name=signature_name)\n  File "/usr/lib/google-cloud-sdk/lib/third_party/ml_sdk/cloud/ml/prediction/prediction_utils.py", line 262, in predict\n    predicted_outputs, original_input=instances, stats=stats, **kwargs)\n  File "/usr/lib/google-cloud-sdk/lib/third_party/ml_sdk/cloud/ml/prediction/frameworks/tf_prediction_lib.py", line 515, in postprocess\n    postprocessed_outputs = list(postprocessed_outputs)\n  File "/usr/lib/google-cloud-sdk/lib/third_party/ml_sdk/cloud/ml/prediction/frameworks/tf_prediction_lib.py", line 152, in rowify\n    "outputs." % sizes_dict)\ncloud.ml.prediction.prediction_utils.PredictionError: There was a problem processing the outputs: Bad output from running tensorflow session: outputs had differing sizes in the batch (outer) dimension. See the outputs and their size: {\'output\': 100, \'other\': 1, \'key\': 100}. Check your model for bugs that effect the size of the outputs. (Error code: 3)\n'
